import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center h-[50vh] items-center  bg-[#6D1C79] text-white">
        <h1 className="text-2xl"> Prubicon </h1>
      </div>
      <div className="flex justify-center  h-[50vh] items-center  bg-[#F5B32F] text-white">
        <h1 className="text-2xl"> Technologies</h1>
      </div>
    </div>
  );
}
